### ISSUE TITLE
this plugins is not work for me ,am i miss something?

### ISSUE THREAD

**Issue by peisheng** [MisumiRize/nightmare-screenshot#1]
var Nightmare = require('nightmare');
var screenshotPlug=require("nightmare-screenshot");

var nightmare = new Nightmare({show: false,height:8000});

var baiduNews = "http://m.news.baidu.com/news#/?_k=tivwq7";
var mobileAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1";
nightmare.viewport(500, 5000)
    .useragent(mobileAgent)
    .goto(baiduNews).evaluate(function (selector) {
     return document.querySelector("ss")
})
    .wait(".newslist-container")
    .use(screenshotPlug.screenshotSelector("e:/baidu.png","body"))  //this is not work
    //.screenshot("e:/new.png")
    .run(function () {
        console.log("ok");
    });

**Comment by MisumiRize** [comment]
Because nightmare v2 has breaking changes, this plugin supports only nightmare v1.
So I've created pull request to support nightmare v2. #2 

``` javascript
var Nightmare = require('nightmare');
var screenshotPlug=require("nightmare-screenshot");

var nightmare = new Nightmare({show: false,height:8000});

var baiduNews = "http://m.news.baidu.com/news#/?_k=tivwq7";
var mobileAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1";
nightmare.viewport(500, 5000)
  .useragent(mobileAgent)
  .goto(baiduNews)
  .use(screenshotPlug.screenshotSelector("e:/baidu.png","body",function() {
    nightmare.end()
      .then(function() {
        console.log("ok");
      });
  }));
```

Please try this code with new version of the plugin.
